version: "3.8"

services:
  lib:
    build: .
    entrypoint: hatch
    depends_on:
      - postgres
    environment:
      PYTHONASYNCIODEBUG: 1

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: password
    volumes:
      - .:/repo

  postgres:
    image: postgres:16-alpine
    ports:
      # Run `docker compose port postgres 5432` to get local port
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
